### ISSUE TITLE
Possible incompatibility introduced with most recent version bump (?)

### ISSUE THREAD

**Issue by fallerd** [winstonjs/winston-transport#247]
Environment:

- Node 10.15.3
- Linux (Docker image running node:10.15.3-slim)
- Winston 3.2.1

Context:

- Weekly deployment of a project using winston 3.2.1 on node 10.15.3 all of a sudden started crashing on startup due to the latest version release on winston-transport.

Appears that bumping the readable-stream version introduced stuff incompatible with older versions of Node (<v12), where globalThis did not exist:

```
ReferenceError: globalThis is not defined
    at Object.<anonymous> (/www/api/node_modules/winston-transport/node_modules/readable-stream/lib/ours/util.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/www/api/node_modules/winston-transport/node_modules/readable-stream/lib/stream.js:31:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

I was able to fix my build pipeline by manually forcing an older version of winston-transport to be used, though this seems a little hacky since I am using winston and winston-transport is only a dependency of it. With that said, I am not sure if this repository or the winston repository is the best place to flag this, but I figured it was worth notifying you all.

**Edited to add**: As MichaelAllenWarner mentioned below, my fix/workaround was to add/specify `"winston-transport": "4.3.0",` in my `package.json`. This happens to be the version that was working for me previously, but probably any version up to 4.7.1 will address this issue as they mentioned.

**Comment by marnick1** [comment]
Hello, I just encountered the same error today with node 10.18.0, on a project using winston 3.8.2 and winston-daily-rotate-file 4.7.1.

Both have a dependency to winston-transport (^4.5.0 & ^4.4.0 respectively).

This seems to be caused by the bump of the "readable-stream" package from v3.x.x to v4.x.x. From the npm page of the package:

> Version 4.x.x
> v4.x.x of readable-stream is a cut from Node 18. This version supports Node 12, 14, 16 and 18, as well as evergreen browsers. 

> Version 3.x.x
> v3.x.x of readable-stream is a cut from Node 10. This version supports Node 6, 8, and 10, as well as evergreen browsers, IE 11 and latest Safari.

Would forcing the "readable-stream" package to v3.6.2 still work with the latest version of winston-transport, or should we force the "winston-transport" package to v4.7.1 instead?

**Comment by MichaelAllenWarner** [comment]
Yes, same issue here.

And to clarify the workaround: add `"winston-transport": "4.7.1"` to your `package.json` dependencies (worked for me, anyway).

**Comment by mahajanankur** [comment]
We are also facing the same issue any other workaround apart from changing Node version?

**Comment by DABH** [comment]
Yeah, as discussed above, there's an issue where readable-stream@4 drops support for old Node versions.

On one hand... none of you should be relying on very old (specifically, unsupported) Node versions for any packages/apps.  My personal opinion is that packages should obey semver, up to Node versions losing support.  Otherwise you get complicated scenarios like this where there's no good way to deal with things (I don't want to cut a major version of winston just because one package drops support for an old/insecure/unsupported Node version).

On the other hand, in this specific case, it looks like readable-stream@4 is causing some test issue in `winston` proper.  So what I've done is release `winston-transport` 4.9.0 that goes back to readable-stream@3 (and hence should work with ancient Node verions), and released new versions of logform and winston, with the newest winston version using the latest logform version and winston-transport 4.9.0.

Going forwards, my plan will be to fix the issues in winston so that we can upgrade the whole stack to use readable-stream@4 (again, this fixes known vulnerabilities and issues, it is important to do this).  Once we do that, I may cut a major version of winston-transport, and a minor version of winston, assuming there are no material changes needed on the winston side to make things work?  But will see what happens.  Community input and contributions are welcome.

Closing for now since this issue is resolved, but please feel free to continue discussion below even though the issue isn't active.
