### ISSUE TITLE
 Misplaced closing tag "</div>" in index.js.html

### ISSUE THREAD

**Issue by lingwu1** [winstonjs/winston-transport#63]
Get ERROR : /winston-transport/coverage/lcov-report/winston-transport/index.js.html: Misplaced closing tag "</div>" (line: 276, col: 6).

**Comment by DABH** [comment]
I don't see that file in this repository.  Perhaps you are running lcov or some tool that's using lcov, on winston-transport?  Feel free to re-open this issue if you can provide minimal steps to reproduce this and if you believe it's only a problem with winston-transport and no other libraries -- otherwise, perhaps this is a bug with lcov or whatever tool you're using to try to parse that file.
