### ISSUE TITLE
Readable Stream Upgrade

### ISSUE THREAD

**Issue by albovieira** [winstonjs/winston-transport#71]
The package readable stream has some break changes from version 2 to 3, I can see that in the master version you already upgrade to version 3. 

Merged PR -> https://github.com/winstonjs/winston-transport/pull/45

Can you publish a new version with these changes?

Thank you for your time, see you.

**Comment by micaeldekleyn** [comment]
Any chance to get an update ? @oreporan / @albovieira did you find a solution ?

**Comment by albovieira** [comment]
Hi guys, this new version is working as expected:
https://github.com/winstonjs/winston-transport/releases/tag/v4.4.0

Try to install this new version, it will work.

**Comment by Quelu** [comment]
Hi @albovieira,

I'm using the last version and this does not work.

In the `v4.4.0` the version listed in the package.json is `^2.3.7` because this tag does not contain this commit: https://github.com/winstonjs/winston-transport/commit/6a3bf79175288328d37c6cf4121d6b39eb68f19f that updates the package `readable-stream` to the version `3.4.0`. 

So we still need a `4.4.1` update of this package to allow the Winston one to update too.

**Comment by albovieira** [comment]
Sorry for my mistake, it has already been some time since my last commentary, you're absolutely right.

**Comment by wbt** [comment]
4.4.1 is now released; hopefully this is fixed!
