### ISSUE TITLE
Npm install Failing

### ISSUE THREAD

**Issue by bhaveshkumarMMT** [winstonjs/winston-transport#73]
Facing following issue on installing winston:-

enoent Error while executing:
#19 20.56 npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/winstonjs/winston-transport.git

Package version:
winston: 3.3.3

**Comment by akshay-mahakalkar** [comment]
Hi @bhaveshkumarMMT 
We are also experiencing the same issue for npm install since yesterday.
--------------------------------------------------------------------------------------------------------
#10 240.7 npm ERR! code ENOENT
#10 240.7 npm ERR! syscall spawn git
#10 240.7 npm ERR! path git
#10 240.7 npm ERR! errno ENOENT
#10 240.7 npm ERR! enoent Error while executing:
#10 240.7 npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/winstonjs/winston-transport.git
#10 240.7 npm ERR! enoent
#10 240.7 npm ERR! enoent
#10 240.7 npm ERR! enoent spawn git ENOENT
#10 240.7 npm ERR! enoent This is related to npm not being able to find a file.
#10 240.7 npm ERR! enoent
-----------------------------------------------------------------------------------------------------------
Here we are using base image of **node:12.19.0-alpine**

Also, we are getting another authontication error when running azure pipelines. This error we are getting on **node:16.0.0-alpine** base image.
-------------------------------------------
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code E401
npm ERR! npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! npm ERR! To correct this please trying logging in again with:
npm ERR! npm ERR!     npm login
npm ERR!
--------------------------------------------
the **.npmrc** file generated is the latest one for both case.

**Comment by IbaiSeco** [comment]
Also experiencing the same issue:

```bash
2021-05-04T15:05:07.458Z [WARNING]: ERR! Error while executing:
                                    npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/winstonjs/winston-transport.git
                                    npm ERR!
                                    npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
                                    npm ERR! Permission denied (publickey).
                                    npm ERR! fatal: Could not read from remote repository.
                                    npm ERR!
                                    npm ERR! Please make sure you have the correct access rights
                                    npm ERR! and the repository exists.
                                    npm ERR!
                                    npm ERR! exited with error code: 128
```

**Comment by bhaveshkumarMMT** [comment]
@IbaiSeco @akshay-mahakalkar git clone ssh://git@github.com/winstonjs/winston-transport.git seems to working for me. But somehow during npm install winston is failing to be installed via ssh

**Comment by gigabytejayesh** [comment]
Hi @bhaveshkumarMMT @IbaiSeco @akshay-mahakalkar

Using the latest version of Winston packages as a fixed version work for me.
        "winston": "3.3.3",
        "winston-daily-rotate-file": "4.5.4"

**Comment by IbaiSeco** [comment]
Hi @gigabytejayesh, @akshay-mahakalkar, @bhaveshkumarMMT 

This issue occurred for me because winstonjs/winston-transport was attempting to be installed via ssh as specified in the package-lock.json as it is a dependancy for aws-amplify/cli and was not actually in use in the package.json file for my application. I am using AWS-Amplify and Amplify however, does not have ssh credentials to access public repositories this way. To solve this error I added winstonjs/winston-transport to package.json with:
```bash
npm i winston-transport
```
And then had to manually update the version to 4.4.0 in the package-lock.json as shown below:
```json
    "winston-transport": {
      "version": "4.4.0",
      "from": "winston-transport@^4.4.0",
      "requires": {
        "logform": "^2.2.0",
        "readable-stream": "^2.3.7",
        "triple-beam": "^1.2.0"
      },
```
The frontend of my react app now builds successfully in the Amplify console.
Cheers, Ibai
